apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.coordinator.volume.pvcname }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.coordinator.volume.size }}