apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "coordinator.serviceAccountName" . }}
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims

  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
